---
- name: Group hosts with DONE status
  hosts: all
  tasks:
    - group_by:
        key: done
- name: Group hosts by kernel, os_family and distrib
  hosts: done
  tasks:
    - group_by:
        key: "{{ ansible_system|lower }}"
    - group_by:
        key: "{{ ansible_distribution|lower }}{{ ansible_distribution_major_version|default(omit) }}"
        parents: "{{ ansible_system|lower }}"
    - group_by:
        key: "{{ ansible_os_family|lower }}"
        parents: "{{ ansible_distribution|lower }}{{ ansible_distribution_major_version|default(omit) }}"
    - group_by:
        key: "xenservers"
      when: ansible_nodename is match("dc[0-9]vt[0-9][0-9]")
    - group_by:
        key: "firewalls"
      when: ansible_nodename is match("dc[0-9]fw[0-9][0-9]")
    - group_by:
        key: "physical"
      when: ansible_product_name is defined

    - debug: msg={{ group_names }}
