---
- name: LINUX setup hosts file
  template: >
    src=hosts.j2
    dest=/etc/hosts
    owner=root
    group=root
    mode=644

- name: LINUX disable IPv6 all
  ansible.posix.sysctl:
    name: net.ipv6.conf.all.disable_ipv6
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes
  when: not is_cloud|default( false, true)

- name: LINUX swapiness
  ansible.posix.sysctl:
    name: vm.swappiness
    value: '10'
    sysctl_set: yes
    state: present
    reload: yes

- name: LINUX disable IPv6 default
  ansible.posix.sysctl:
    name: net.ipv6.conf.default.disable_ipv6
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes
  when: not is_cloud|default( false, true)

- name: LINUX Ensure a en_US locale exists
  community.general.locale_gen:
    name: en_US.UTF-8
    state: present

- name: LINUX Ensure a ru_RU locale exists
  community.general.locale_gen:
    name: ru_RU.UTF-8
    state: present

- name: LINUX Add or modify hard nofile limits for wildcard domain
  community.general.pam_limits:
    domain: '*'
    limit_type: hard
    limit_item: nofile
    value: "200000"

- name: LINUX Add or modify soft nofile limits for wildcard domain
  community.general.pam_limits:
    domain: '*'
    limit_type: soft
    limit_item: nofile
    value: "100000"

- name: LINUX Setup resolv.conf domain
  lineinfile: >
    path=/etc/resolv.conf
    regexp='search'
    line='search ps'
    create=yes
    mode="644"

- name: LINUX Setup resolv.conf parametrs
  lineinfile: >
    path=/etc/resolv.conf
    regexp='options'
    line='options timeout:1 attempts:1'
    create=yes
    mode="644"
