---
- name: install zabbix-agent
  apt:
    name:
      - zabbix-agent
- name: agent config
  template: >
    src=zabbix_agentd.conf.j2
    dest=/etc/zabbix/zabbix_agentd.conf
    owner=root
    group=root
    mode="644"
  notify:
    - restart zabbix-agent